apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tesseract-ocr
  name: tesseract-ocr
spec:
  containers:
  - image: olrich/tesseract-ocr-service:1.0
    name: tesseract-ocr
    ports:
    - containerPort: 9099
    resources: {}
  dnsPolicy: ClusterFirst
