apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ocr-service
  name: ocr-service
spec:
  ports:
  - name: 80-9099
    port: 80
    protocol: TCP
    targetPort: 9099
  selector:
    run: tesseract-ocr
  type: LoadBalancer
status:
  loadBalancer: {}
